x-common: &common
  build: .
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
  environment:
    DISPLAY: $DISPLAY
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix
    - ./input:/app/input
    - ./output:/app/output

services:
  app:
    <<: *common
    profiles:
      - prod
  test:
    <<: *common
    profiles:
      - test
    command: poetry run python -m app.vdi_perf_test
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./app/logs:/app/app/logs
